# generated by datamodel-codegen:
#   filename:  sample.json
#   timestamp: 2026-03-17T16:38:21+00:00

from __future__ import annotations

from pydantic import BaseModel
from typing import Any

class Field(BaseModel):
    id: str
    name: str
    type: str
    value: str
    checked: bool
    multiple: bool
    width: str
    height: str
    required: bool


class File(BaseModel):
    name: str
    file: str
    fields: list[Field]
    autoGroupedFieldsFill: bool
    additionalFiles: Any


class MultipleStampSery(BaseModel):
    stampSeries: str
    seriesQuantity: str


class StampUpload(BaseModel):
    state: str
    denomination: str
    firstPartyName: str
    secondPartyName: str
    stampSerial: str
    stampFile: str


class DocumentDetail(BaseModel):
    loanNumber: str
    sanctionNumber: str
    registrationType: str
    state: str
    branchName: str
    branchAddress: str
    dateOfSanction: str
    emiAmount: str
    rateOfInterest: str
    sanctionAmount: str
    tenure: str
    typeOfDebt: str
    accountClosedFlag: str
    fundType: str
    sanctionCurrency: str
    creditSubtype: str
    facilityName: str
    amountOverdue: str
    otherChargeAmount: str
    debtStartDate: str
    interestAmount: str
    oldDebtRefNo: str
    principalOutstanding: str
    loanRemark: str
    totalOutstandingAmount: str
    creditorBusinessUnit: str
    drawingPower: str
    daysPastDue: str
    docRefNo: str
    expiryDateEbg: str
    claimExpiryDate: str
    contractRefNo: str
    vendorCode: str
    portalId: str
    event: str


class StampDatum(BaseModel):
    firstParty: str
    secondParty: str
    stampDutyAmount: str
    considerationPrice: str
    descriptionOfDocument: str
    stampDutyPaidBy: str
    articleCode: str
    firstPartyPin: str
    secondPartyPin: str
    firstPartyOVDType: str
    firstPartyOVDValue: str
    secondPartyOVDType: str
    secondPartyOVDValue: str


class Participant(BaseModel):
    fullName: str
    contactPersonName: str
    contactRelation: str
    emailId: str
    mobileNumber: str
    dob: str
    legalConstitution: str
    alternateEmailId: str
    alternateMobileNumber: str
    officialDocType: str
    officialDocId: str
    registeredAddress: str
    registeredPinCode: str
    designation: str
    communicationAddress: str
    communicationAddressPinCode: str
    cin: str
    kin: str
    partyType: str
    isIndividual: str
    signatoryGender: str
    businessUnit: str


class NeslParty(BaseModel):
    fullName: str
    contactPersonName: str
    contactRelation: str
    emailId: str
    mobileNumber: str
    dob: str
    legalConstitution: str
    alternateEmailId: str
    alternateMobileNumber: str
    officialDocType: str
    officialDocId: str
    registeredAddress: str
    registeredPinCode: str
    designation: str
    communicationAddress: str
    communicationAddressPinCode: str
    cin: str
    kin: str
    partyType: str
    isIndividual: str
    signatoryGender: str


class NeslSecurity(BaseModel):
    securityDescription: str
    assetsType: str
    chargeType: str
    assetId: str
    doc: str
    dov: str
    cersaiId: str
    rocChargeId: str
    securityValue: str
    abc: str


class NeslData(BaseModel):
    documentDetail: DocumentDetail
    stampData: list[StampDatum]
    participants: list[Participant]
    neslParties: list[NeslParty]
    neslSecurities: list[NeslSecurity]


class WorkflowPaymentCollectionConfig(BaseModel):
    amount: str


class GpsConfig(BaseModel):
    applyLocationRestriction: bool
    allowedLatitude: str
    allowedLongitude: str
    permissibleRadius: int
    applyLocationAccuracy: bool
    accuracyThreshold: int


class AadhaarConfig(BaseModel):
    verifyName: bool
    verifySmartName: bool
    verifyPincode: str
    verifyYob: int
    verifyTitle: str
    verifyState: str
    verifyGender: str


class OfflineSignConfig(BaseModel):
    mobileNumber: str
    pan: str
    signerId: str
    verifyName: bool
    verifySmartName: bool
    verifyPincode: str
    verifyState: str
    verifyYob: int
    verifyTitle: str
    verifyGender: str


class DscConfig(BaseModel):
    verifyName: bool
    verifySmartName: bool
    verifyPincode: str
    verifyState: str


class NeslConfig(BaseModel):
    verifyName: bool
    verifySmartName: bool
    verifyPincode: str
    verifyYob: int
    verifyTitle: str
    verifyState: str
    verifyGender: str


class Invitee(BaseModel):
    name: str
    email: str
    phone: str
    groupId: str
    groupName: str
    completionThreshold: str
    organizationName: str
    defaultLanguageSelect: str
    faceMatchImage: str
    workflowPaymentCollectionConfig: WorkflowPaymentCollectionConfig
    gpsConfig: GpsConfig
    aadhaarConfig: AadhaarConfig
    offlineSignConfig: OfflineSignConfig
    dscConfig: DscConfig
    neslConfig: NeslConfig


class CcItem(BaseModel):
    name: str
    email: str


class Model(BaseModel):
    profileId: str
    file: File
    stampSeries: str
    multipleStampSeries: list[MultipleStampSery]
    seriesGroup: str
    stampValue: str
    stampUpload: StampUpload
    revenueStampSeries: str
    revenueStampQuantity: str
    neslData: NeslData
    invitees: list[Invitee]
    cc: list[CcItem]
    irn: str
