# generated by datamodel-codegen:
#   filename:  sample_response.json
#   timestamp: 2026-03-17T16:44:28+00:00

from __future__ import annotations

from pydantic import BaseModel


class Message(BaseModel):
    code: str
    message: str


class Invitee(BaseModel):
    name: str
    email: str
    phone: str
    signUrl: str
    active: bool
    expiryDate: str


class Data(BaseModel):
    documentId: str
    irn: str
    invitees: list[Invitee]


class Model(BaseModel):
    status: int
    messages: list[Message]
    data: Data
