# generated by datamodel-codegen:
#   filename:  request.json
#   timestamp: 2026-03-18T06:12:23+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class DisplayOnPage(Enum):
    first = 'first'
    last = 'last'
    all = 'all'
    custom = 'custom'


class SignCoordinate(BaseModel):
    llx: int
    lly: int
    urx: int
    ury: int


class CustomerNotificationMode(Enum):
    SMS = 'SMS'
    WHATSAPP = 'WHATSAPP'
    ALL = 'ALL'


class SignatureType(Enum):
    dsc = 'dsc'
    aadhaar = 'aadhaar'
    external = 'external'
    external_sign = 'external_sign'
    aadhaar_with_dependents = 'aadhaar_with_dependents'
    electronic_with_dependents = 'electronic_with_dependents'
    electronic = 'electronic'
    document_review = 'document_review'


class NoteOnPage(Enum):
    first = 'first'
    last = 'last'
    all = 'all'
    custom = 'custom'


class SignOnPage(Enum):
    first = 'first'
    last = 'last'
    all = 'all'
    custom = 'custom'


class EstampRequest(BaseModel):
    tags: dict[str, int] | None = None
    note_content: str | None = None
    note_on_page: NoteOnPage | None = None
    sign_on_page: SignOnPage | None = None


class PostSigningReceiver(BaseModel):
    identifier: str


class Operation(Enum):
    AND = 'AND'
    OR = 'OR'


class Field(Enum):
    NAME = 'NAME'
    YOB = 'YOB'
    AADHAAR = 'AADHAAR'
    GENDER = 'GENDER'


class MatchType(Enum):
    EXACT = 'EXACT'
    FUZZY = 'FUZZY'


class Condition(BaseModel):
    field: Field
    matchType: MatchType
    value: str
    threshold: int | None = None
    inputValue: str | None = None
    fuzzyScore: int | None = None
    multiPropertyRule: dict[str, list[str]] | None = None


class Rule(BaseModel):
    operation: Operation
    conditions: list[Condition]


class SignatureVerification(BaseModel):
    abortOnFail: bool
    maxAttempt: int
    rules: list[Rule]


class Type(Enum):
    AT_LEAST_N_ACTIONERS = 'AT_LEAST_N_ACTIONERS'
    REQUIRED_UNITS = 'REQUIRED_UNITS'


class Signer(BaseModel):
    signingPartyId: str | None = None
    identifier: str | None = None
    name: str | None = None
    signingStatus: str | None = None
    signedAt: str | None = None


class SigningConditionItem(BaseModel):
    type: Type | None = None
    signers: list[Signer] | None = None
    identifiers: list[str] | None = None
    value: int | None = None
    conditionPassed: bool | None = None


class Condition1(BaseModel):
    signingCondition: list[SigningConditionItem] | None = None


class SigningConditionRequest(BaseModel):
    conditions: list[Condition1] | None = None


class SignType(Enum):
    dsc = 'dsc'
    aadhaar = 'aadhaar'
    external = 'external'
    external_sign = 'external_sign'
    aadhaar_with_dependents = 'aadhaar_with_dependents'
    electronic_with_dependents = 'electronic_with_dependents'
    electronic = 'electronic'
    document_review = 'document_review'


class SignatureMode(Enum):
    otp = 'otp'
    slate = 'slate'
    kyc = 'kyc'
    otp_certified = 'otp_certified'
    slate_certified = 'slate_certified'
    esign_3 = 'esign_3'
    esign_3s = 'esign_3s'
    nesl_aadhaar_sign = 'nesl_aadhaar_sign'


class Type1(Enum):
    geo_location = 'geo_location'
    consent = 'consent'


class SigningAddon(BaseModel):
    type: Type1
    performEnrichment: bool | None = None
    optional: bool | None = None


class Signer1(BaseModel):
    identifier: str
    reason: str | None = None
    sign_type: SignType | None = None
    signature_mode: SignatureMode | None = None
    name: str | None = None
    signer_tag: str | None = None
    signing_addons: list[SigningAddon] | None = None
    index: int | None = None


class Model(BaseModel):
    file_name: str
    will_self_sign: bool | None = None
    signatory: str | None = None
    expire_in_days: int | None = None
    callback: str | None = None
    comment: str | None = None
    display_on_page: DisplayOnPage | None = None
    sign_coordinates: dict[str, dict[str, list[SignCoordinate]]] | None = None
    notify_signers: bool | None = None
    customer_notification_mode: CustomerNotificationMode | None = None
    signature_type: SignatureType | None = None
    estamp_request: EstampRequest | None = None
    generate_access_token: bool | None = None
    post_signing_receivers: list[PostSigningReceiver] | None = None
    signature_verification: dict[str, SignatureVerification] | None = None
    signing_condition_request: SigningConditionRequest | None = None
    include_authentication_url: bool | None = None
    reference_id: str | None = None
    signers: list[Signer1] | None = None
    sequential: bool | None = None
    send_sign_link: bool | None = None
    file_data: str
    require_full_document_review: bool | None = None
