# generated by datamodel-codegen:
#   filename:  response.json
#   timestamp: 2026-03-18T06:19:26+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, RootModel


class AgreementType(Enum):
    inbound = 'inbound'
    outbound = 'outbound'


class AgreementStatus(Enum):
    draft = 'draft'
    requested = 'requested'
    completed = 'completed'
    expired = 'expired'
    failed = 'failed'


class SelfSignType(Enum):
    dsc = 'dsc'
    aadhaar = 'aadhaar'
    external = 'external'
    external_sign = 'external_sign'
    aadhaar_with_dependents = 'aadhaar_with_dependents'
    electronic_with_dependents = 'electronic_with_dependents'
    electronic = 'electronic'
    document_review = 'document_review'


class SelfSignMode(Enum):
    otp = 'otp'
    slate = 'slate'
    kyc = 'kyc'
    otp_certified = 'otp_certified'
    slate_certified = 'slate_certified'
    esign_3 = 'esign_3'
    esign_3s = 'esign_3s'
    nesl_aadhaar_sign = 'nesl_aadhaar_sign'


class Status(Enum):
    requested = 'requested'
    signed = 'signed'
    expired = 'expired'
    sequenced = 'sequenced'
    cancelled = 'cancelled'
    removed = 'removed'
    failed = 'failed'
    skipped = 'skipped'


class Type(Enum):
    self = 'self'
    org = 'org'
    signatory = 'signatory'


class SignatureType(Enum):
    dsc = 'dsc'
    aadhaar = 'aadhaar'
    external = 'external'
    external_sign = 'external_sign'
    aadhaar_with_dependents = 'aadhaar_with_dependents'
    electronic_with_dependents = 'electronic_with_dependents'
    electronic = 'electronic'
    document_review = 'document_review'


class SignatureMode(Enum):
    otp = 'otp'
    slate = 'slate'
    kyc = 'kyc'
    otp_certified = 'otp_certified'
    slate_certified = 'slate_certified'
    esign_3 = 'esign_3'
    esign_3s = 'esign_3s'
    nesl_aadhaar_sign = 'nesl_aadhaar_sign'


class RequesterType(Enum):
    individual = 'individual'
    org = 'org'


class Channel(Enum):
    web = 'web'
    android = 'android'
    ios = 'ios'
    windows = 'windows'
    android_partner = 'android_partner'
    api = 'api'
    android_sdk = 'android_sdk'


class SignRequestDetails(BaseModel):
    name: str | None = None
    requested_on: AwareDatetime | None = None
    expire_on: AwareDatetime | None = None
    identifier: str | None = None
    requester_type: RequesterType | None = None
    channel: Channel | None = None
    cancel_reason: str | None = None
    require_full_document_review: bool | None = None


class OtherDocDetails(BaseModel):
    web_hook_available: bool | None = None


class AccessToken(BaseModel):
    entityId: str | None = None
    id: str | None = None
    validTill: AwareDatetime | None = None
    createdAt: AwareDatetime | None = None


class DocumentAdditionalInfo(BaseModel):
    id: str | None = None
    docId: str | None = None
    subUserId: str | None = None
    postSigningReceivers: str | None = None


class CustomerNotificationMode(Enum):
    SMS = 'SMS'
    WHATSAPP = 'WHATSAPP'
    ALL = 'ALL'


class DisplayOnPage(Enum):
    first = 'first'
    last = 'last'
    all = 'all'
    custom = 'custom'


class PageMetaData(BaseModel):
    width: float | None = None
    height: float | None = None


class PdfMetaData(BaseModel):
    pageMetaData: dict[str, PageMetaData] | None = None


class Operation(Enum):
    AND = 'AND'
    OR = 'OR'


class Condition(BaseModel):
    field: str | None = None
    match: str | None = None
    actualValue: str | None = None
    expectedValue: str | None = None
    fuzzyScore: int | None = None
    result: str | None = None


class RuleResult(BaseModel):
    ruleId: int | None = None
    result: str | None = None
    operation: Operation | None = None
    conditions: list[Condition] | None = None


class SignatureVerificationResponse(BaseModel):
    overallResult: str | None = None
    ruleResults: list[RuleResult] | None = None


class Type2(Enum):
    geo_location = 'geo_location'
    consent = 'consent'


class Status2(Enum):
    requested = 'requested'
    success = 'success'
    skipped = 'skipped'


class SeedMethod(Enum):
    seeding = 'seeding'
    user_input = 'user_input'


class SigningFeature(BaseModel):
    featureId: str | None = None
    result: str | None = None
    type: Type2 | None = None
    status: Status2 | None = None
    optional: bool | None = None
    performEnrichment: bool | None = None
    seed_method: SeedMethod | None = None
    seeding_required: bool | None = None
    existing_user_name: str | None = None


class SignType(Enum):
    dsc = 'dsc'
    aadhaar = 'aadhaar'
    external = 'external'
    external_sign = 'external_sign'
    aadhaar_with_dependents = 'aadhaar_with_dependents'
    electronic_with_dependents = 'electronic_with_dependents'
    electronic = 'electronic'
    document_review = 'document_review'


class SigningAddon(BaseModel):
    type: Type2
    performEnrichment: bool | None = None
    optional: bool | None = None


class PreferredSeedMethod(Enum):
    seeding = 'seeding'
    user_input = 'user_input'


class Coord(BaseModel):
    llx: int
    lly: int
    urx: int
    ury: int


class Signer(BaseModel):
    name: str | None = None
    identifier: str | None = None
    reminder: list[int] | None = None
    signType: SignType | None = None
    signatureMode: SignatureMode | None = None
    optional: bool | None = None
    signing_addons: list[SigningAddon] | None = None
    expiredInDays: int | None = None
    preferredSeedMethod: PreferredSeedMethod | None = None
    coords: dict[str, list[Coord]] | None = None


class DraftSigner(BaseModel):
    signer: Signer | None = None


class NoteOnPage(Enum):
    first = 'first'
    last = 'last'
    all = 'all'
    custom = 'custom'


class SignOnPage(Enum):
    first = 'first'
    last = 'last'
    all = 'all'
    custom = 'custom'


class EstampRequest(BaseModel):
    tags: dict[str, int] | None = None
    note_content: str | None = None
    note_on_page: NoteOnPage | None = None
    sign_on_page: SignOnPage | None = None


class Field(Enum):
    NAME = 'NAME'
    YOB = 'YOB'
    AADHAAR = 'AADHAAR'
    GENDER = 'GENDER'


class MatchType(Enum):
    EXACT = 'EXACT'
    FUZZY = 'FUZZY'


class Condition1(BaseModel):
    field: Field
    matchType: MatchType
    value: str
    threshold: int | None = None
    inputValue: str | None = None
    fuzzyScore: int | None = None
    multiPropertyRule: dict[str, list[str]] | None = None


class Rule(BaseModel):
    operation: Operation
    conditions: list[Condition1]


class SignatureVerification1(BaseModel):
    abortOnFail: bool
    maxAttempt: int
    rules: list[Rule]


class SignatureVerification(RootModel[dict[str, SignatureVerification1]]):
    root: dict[str, SignatureVerification1]


class Type4(Enum):
    AT_LEAST_N_ACTIONERS = 'AT_LEAST_N_ACTIONERS'
    REQUIRED_UNITS = 'REQUIRED_UNITS'


class Signer1(BaseModel):
    signingPartyId: str | None = None
    identifier: str | None = None
    name: str | None = None
    signingStatus: str | None = None
    signedAt: str | None = None


class SigningConditionItem(BaseModel):
    type: Type4 | None = None
    signers: list[Signer1] | None = None
    identifiers: list[str] | None = None
    value: int | None = None
    conditionPassed: bool | None = None


class Condition2(BaseModel):
    signingCondition: list[SigningConditionItem] | None = None


class SigningConditionRequest(BaseModel):
    conditions: list[Condition2] | None = None


class SelfDetails(BaseModel):
    name: str | None = None
    status: Status | None = None
    type: Type | None = None
    signature_type: SignatureType | None = None
    signature_mode: SignatureMode | None = None
    identifier: str | None = None
    reason: str | None = None
    expire_on: AwareDatetime | None = None
    signature_verification_response: SignatureVerificationResponse | None = None
    aadhaar_mode: str | None = None
    authentication_url: str | None = None
    signing_features: list[SigningFeature] | None = None


class SigningParty(BaseModel):
    name: str | None = None
    status: Status | None = None
    type: Type | None = None
    signature_type: SignatureType | None = None
    signature_mode: SignatureMode | None = None
    identifier: str | None = None
    reason: str | None = None
    expire_on: AwareDatetime | None = None
    signature_verification_response: SignatureVerificationResponse | None = None
    aadhaar_mode: str | None = None
    authentication_url: str | None = None
    signing_features: list[SigningFeature] | None = None


class Draft(BaseModel):
    file_name: str | None = None
    signers: list[DraftSigner] | None = None
    post_signing_receivers: list[str] | None = None
    customer_notification_mode: CustomerNotificationMode | None = None
    sequential: bool | None = None
    comment: str | None = None
    send_sign_link: bool | None = None
    display_on_page: DisplayOnPage | None = None
    notify_signers: bool | None = None
    estamp_request: EstampRequest | None = None
    signature_verification: SignatureVerification | None = None
    signing_condition_request: SigningConditionRequest | None = None
    reference_id: str | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None
    pdfMetaData: PdfMetaData | None = None
    consents: list[str] | None = None


class Model(BaseModel):
    id: str | None = None
    is_agreement: bool | None = None
    agreement_type: AgreementType | None = None
    agreement_status: AgreementStatus | None = None
    file_name: str | None = None
    created_at: AwareDatetime | None = None
    self_signed: bool | None = None
    self_sign_type: SelfSignType | None = None
    self_sign_mode: SelfSignMode | None = None
    self_details: SelfDetails | None = None
    no_of_pages: int | None = None
    signing_parties: list[SigningParty] | None = None
    sign_request_details: SignRequestDetails | None = None
    other_doc_details: OtherDocDetails | None = None
    access_token: AccessToken | None = None
    attached_estamp_details: dict[str, list[str]] | None = None
    document_additional_info: DocumentAdditionalInfo | None = None
    draft: Draft | None = None
